### ISSUE TITLE
Is firebase really required?

### ISSUE THREAD

**Issue by kaif-azzan** [SandeepKrSuman/medcare-server#1]
Hey, i saw a few firebase credentials required in the .env file, is that really required? cz you had already used mongodb no?

**Comment by kaif-azzan** [comment]
Anyway;s here my actual error, I tried adding the key yet i get the same error
![Screenshot 2024-04-25 190056](https://github.com/SandeepKrSuman/medcare-server/assets/114873154/34e8f288-0f9a-4f84-a1a5-dc1475a6b47b)

**Comment by SandeepKrSuman** [comment]
> Hey, i saw a few firebase credentials required in the .env file, is that really required? cz you had already used mongodb no?

Firebase is utilized solely for **storing prescription files** (PDFs/images) from the doctor's dashboard for ease of implementation. Find the code snippet in [uploadPrescription()](https://github.com/SandeepKrSuman/medcare-server/blob/master/controllers/doctor.js#L59).

You may opt for alternative methods according to your preference. In such cases, Firebase credentials can be omitted or replaced accordingly.

It's crucial to note that Firebase is exclusively employed for this specific purpose and isn't utilized elsewhere in the project. The application should operate without requiring Firebase credentials as long as this functionality remains inactive. Feel free to make adjustments as necessary based on your database preferences.

**Comment by SandeepKrSuman** [comment]
> Anyway;s here my actual error, I tried adding the key yet i get the same error ![Screenshot 2024-04-25 190056](https://private-user-images.githubusercontent.com/114873154/325630664-34e8f288-0f9a-4f84-a1a5-dc1475a6b47b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTIxNzYsIm5iZiI6MTcxNDA1MTg3NiwicGF0aCI6Ii8xMTQ4NzMxNTQvMzI1NjMwNjY0LTM0ZThmMjg4LTBmOWEtNGY4NC1hMWE1LWRjMTQ3NWE2YjQ3Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxMzMxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzI0MWYyOTk2ZDM4YTliN2RiNjFhMDAzMGYxMjE2OTczOWM5OWYyNDc1ZWFjYTdkMmRkOTM5NDM0OTU0ZjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oy_t2bkVzK0hgDB1-Htxg4DzBa0yJi_ZnU9PdsqyYEI)

Looks like the environment variables are not set / read properly. Make sure, you have a `.env` file in the root of the project directory. Take a look at the `.env.example` file to setup the environment variables.

Take a look at this [reference](https://stackoverflow.com/questions/58673430/error-secretorprivatekey-must-have-a-value)

**Comment by kaif-azzan** [comment]
![image](https://github.com/SandeepKrSuman/medcare-server/assets/114873154/550ed5d0-4107-4148-b352-2c05686db1e3)
does this seem right to you?
![image](https://github.com/SandeepKrSuman/medcare-server/assets/114873154/004745ff-c04c-4a23-9e20-f175d30e4454)

**Comment by SandeepKrSuman** [comment]
Could you please console.log the values of the environment variables from both `/models/auth.js` and `controllers/authController.js`, and verify whether you can access the values set inside the .env file? If it logs `null` or `undefined`, it indicates that these values are not accessible. Please try debugging. One of the solutions I've seen involves using ES6 string literals like `${process.env.ACCESS_SECRET}` ([reference](https://stackoverflow.com/questions/58673430/error-secretorprivatekey-must-have-a-value#:~:text=Remove%20the%20process.env.JWT_SECRET_KEY%20and%20do%20it%20this%20way%3A%20%24%7Bprocess.env.JWT_SECRET_KEY%7D)), but I'm not certain whether it will work. Please give it a try and let me know the outcome.

**Comment by SandeepKrSuman** [comment]
The exact repository code seems to be functioning correctly on my end. I'd suggest re-running the application to see if the issue persists. As a workaround, you might consider temporarily using hardcoded strings instead of reading from the `.env` file to see if the application functions properly. If it does, then we'll need to investigate the implementation of the logic handling `.env` files, as the problem may lie there. Please try debugging accordingly. Additionally, it's important to note that using hardcoded keys is not secure; this approach is solely for testing purposes.

**Comment by kaif-azzan** [comment]
There seems to be some problem with env file on my end, i switched .env variables with hardcoded strings and it seem;s to work for now but some function seems to be a problem ill try debugging them and let you know, thanks.

**Comment by kaif-azzan** [comment]
Heyyy it seems to work fine but how do i login as admin?

**Comment by kaif-azzan** [comment]
Okay so i tried changing the verified status from false to true for doctor in databse but when i go to book appointments im not able to load the doctor list i suspect when an admin register's a doctor they enter extra variables, as you can see it outputs a list of doctor in console.

![image](https://github.com/SandeepKrSuman/medcare-server/assets/114873154/b56e7274-1f82-4c79-9e84-f8dcde7f8109)

**Comment by SandeepKrSuman** [comment]
> Heyyy it seems to work fine but how do i login as admin?

Go through the front-end repo. The following issue explains how to log in as admin:

https://github.com/SandeepKrSuman/medcare/issues/2#issue-2177045590

**Comment by SandeepKrSuman** [comment]
> Okay so i tried changing the verified status from false to true for doctor in databse but when i go to book appointments im not able to load the doctor list i suspect when an admin register's a doctor they enter extra variables, as you can see it outputs a list of doctor in console.
> 
> ![image](https://private-user-images.githubusercontent.com/114873154/325678815-b56e7274-1f82-4c79-9e84-f8dcde7f8109.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjE0MTEsIm5iZiI6MTcxNDA2MTExMSwicGF0aCI6Ii8xMTQ4NzMxNTQvMzI1Njc4ODE1LWI1NmU3Mjc0LTFmODItNGM3OS05ZTg0LWY4ZGNkZTdmODEwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNjA1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGQ2Y2QwMmU5MjYwMTMxNjMzYWVmYWY5NTg4MTAxZjM1M2JjYTgzNGYwYzdmNWQ0ZDUzZGYxMjJhNjU4ODM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uJvZ5wTJO74BhANUuKxPCPmMjQr8h1s0xG56gfLtWtc)

You're absolutely right. Logging in as an admin will streamline this task. From the admin dashboard, you'll have the capability to add individual doctors to the doctor's list after verification. Additionally, there are other fields that need to be filled out by the admin, such as specifying the days of the week the doctor is available, and so forth. Based on this information, it will be displayed on the respective page accordingly. Furthermore, take a look at the schemas to get a clear grasp of how the data is stored in the database and which fields are required.

**Comment by SandeepKrSuman** [comment]
I'm closing this particular issue as complete. If you encounter any further challenges, please feel free to create another issue.

I highly **recommend creating separate issues for each distinct problem**.

Additionally, please ensure that frontend-related issues are created within the [frontend repository](https://github.com/SandeepKrSuman/medcare), while backend-related issues are created within the backend repository i.e. in this repo itself.

This approach will keep the conversation clean, relevant, and easier to understand, thus facilitating the resolution of the originating problem.

Thank you!
Happy Coding 🚀
